# -*- coding: utf-8 -*-
source 'http://rubygems.org'

version = File.read(File.expand_path("../../TENGINE_VERSION", __FILE__)).strip

# すぐにパッチが出る事を予想しています。リリース近くなったらバージョンを固定します。
gem 'rails', '~> 3.2.3'
gem 'sass' , '~> 3.1.18'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem "selectable_attr", "~> 0.3.14"
gem "selectable_attr_rails", "~> 0.3.14"

gem "mongoid", "~> 3.0.0", "< 3.0.20"

gem "kaminari", "~> 0.13.0"

gem "tengine_event"          , "~> #{version}"
gem "tengine_core"           , "~> #{version}"
gem "tengine_resource"       , "~> #{version}"
gem "tengine_resource_ec2"   , "~> #{version}"
gem "tengine_resource_wakame", "~> #{version}"
gem "tengine_job"            , "~> #{version}"

gem "wakame-adapters-tengine", "~> 0.0.0"

gem "daemons", "~> 1.1.4"

gem 'devise'
gem "rails_admin"

group :test, :development do
  gem "factory_girl"

  gem "rails3-generators", "~> 0.17.4"
  gem "rspec-rails", "~> 2.10.1"
  gem "capybara", "~> 1.1.1"

  gem "ZenTest", "< 4.8.4" # 4.8.4 と 4.9.0 がおかしい
  gem "autotest-rails"

  # gem "rcov", ">= 0"
  gem "simplecov", "~> 0.6.4"

  gem 'capistrano'       , "~> 2.9.0"
  gem 'capistrano-ext'   , "~> 1.2.1"
  gem 'capistrano_colors', "~> 0.5.5"

  gem "pry"
  gem "pry-nav"
end

group :js_engine do
  if RUBY_PLATFORM =~ /linux/ then
    gem 'therubyracer', "~> 0.9.4"
  end
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.2.5"
  gem 'coffee-rails', "~> 3.2.2"
  gem 'uglifier', "~> 1.2.4"
end

gem 'jquery-rails', "~> 2.0.2"
