# -*- coding: utf-8 -*-
source 'http://rubygems.org'

# すぐにパッチが出る事を予想しています。リリース近くなったらバージョンを固定します。
gem 'rails', '~> 3.1.0'
gem 'sass' , '~> 3.1.11'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem "selectable_attr", "~> 0.3.14"
gem "selectable_attr_rails", "~> 0.3.14"

gem "mongoid", "~> 2.3.3"
gem "mongo", "~> 1.5.2"
gem "bson_ext", "~> 1.5.2"

gem "kaminari", "~> 0.12.4"

gem "tengine_event"   , "~> 0.4.1"
gem "tengine_core"    , "~> 0.5.20"
gem "tengine_resource", "~> 0.5.11"
gem "tengine_job"     , "~> 0.6.14"

gem "wakame-adapters-tengine", "~> 0.0.0"

gem "daemons", "~> 1.1.4"

group :test, :development do
  gem "rails3-generators", "~> 0.17.4"
  gem "rspec-rails", "~> 2.6.1"
  gem "capybara", "~> 1.1.1"

  gem "ZenTest", "~> 4.5.0"
  gem "autotest-rails", "~> 4.1.1"

  # gem "rcov", ">= 0"
  gem "simplecov", "~> 0.5.3"

  gem 'capistrano'       , "~> 2.9.0"
  gem 'capistrano-ext'   , "~> 1.2.1"
  gem 'capistrano_colors', "~> 0.5.5"
end

group :js_engine do
  if RUBY_PLATFORM =~ /linux/ then
    gem 'therubyracer', "~> 0.9.4"
  end
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier', "~> 1.0.3"
end

gem 'jquery-rails', "~> 1.0.14"
