require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Tengine::Test::ScriptsController do

  # This should return the minimal set of attributes required to create a valid
  # Tengine::Test::Script. As you add validations to Tengine::Test::Script, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { :kind => '01', :code => 'true' }
  end

  describe "GET index" do
    it "assigns all tengine_test_scripts as @tengine_test_scripts" do
      Tengine::Test::Script.delete_all
      script = Tengine::Test::Script.create! valid_attributes
      get :index
      scripts = assigns(:scripts)
      scripts.to_a.should eq([script])
    end
  end

  describe "GET show" do
    it "assigns the requested script as @script" do
      script = Tengine::Test::Script.create! valid_attributes
      get :show, :id => script.id.to_s
      assigns(:script).should eq(script)
    end
  end

  describe "GET new" do
    it "assigns a new script as @script" do
      get :new
      assigns(:script).should be_a_new(Tengine::Test::Script)
    end
  end

  describe "GET edit" do
    it "assigns the requested script as @script" do
      script = Tengine::Test::Script.create! valid_attributes
      get :edit, :id => script.id.to_s
      assigns(:script).should eq(script)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tengine::Test::Script" do
        expect {
          post :create, :script => valid_attributes
        }.to change(Tengine::Test::Script, :count).by(1)
      end

      it "assigns a newly created script as @script" do
        post :create, :script => valid_attributes
        assigns(:script).should be_a(Tengine::Test::Script)
        assigns(:script).should be_persisted
      end

      it "redirects to the created script" do
        post :create, :script => valid_attributes
        response.should redirect_to(Tengine::Test::Script.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved script as @script" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Test::Script.any_instance.stub(:save).and_return(false)
        post :create, :script => {}
        assigns(:script).should be_a_new(Tengine::Test::Script)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Test::Script.any_instance.stub(:save).and_return(false)
        post :create, :script => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested script" do
        script = Tengine::Test::Script.create! valid_attributes
        # Assuming there are no other tengine_test_scripts in the database, this
        # specifies that the Tengine::Test::Script created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tengine::Test::Script.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => script.id, :script => {'these' => 'params'}
      end

      it "assigns the requested script as @script" do
        script = Tengine::Test::Script.create! valid_attributes
        put :update, :id => script.id, :script => valid_attributes
        assigns(:script).should eq(script)
      end

      it "redirects to the script" do
        script = Tengine::Test::Script.create! valid_attributes
        put :update, :id => script.id, :script => valid_attributes
        response.should redirect_to(script)
      end
    end

    describe "with invalid params" do
      it "assigns the script as @script" do
        script = Tengine::Test::Script.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Test::Script.any_instance.stub(:save).and_return(false)
        put :update, :id => script.id.to_s, :script => {}
        assigns(:script).should eq(script)
      end

      it "re-renders the 'edit' template" do
        script = Tengine::Test::Script.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Test::Script.any_instance.stub(:save).and_return(false)
        put :update, :id => script.id.to_s, :script => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested script" do
      script = Tengine::Test::Script.create! valid_attributes
      expect {
        delete :destroy, :id => script.id.to_s
      }.to change(Tengine::Test::Script, :count).by(-1)
    end

    it "redirects to the tengine_test_scripts list" do
      script = Tengine::Test::Script.create! valid_attributes
      delete :destroy, :id => script.id.to_s
      response.should redirect_to(tengine_test_scripts_url)
    end
  end

end
