# encoding: utf-8

require 'rubygems'
require 'bundler'
begin
  Bundler.setup(:default, :development)
rescue Bundler::BundlerError => e
  $stderr.puts e.message
  $stderr.puts "Run `bundle install` to install missing gems"
  exit e.status_code
end
require 'rake'

require 'jeweler'
Jeweler::Tasks.new do |gem|
  # gem is a Gem::Specification... see http://docs.rubygems.org/read/chapter/20 for more options
  gem.name = "tengine_event"
  gem.homepage = "https://github.com/tengine/tengine_event"
  gem.license = "MPL2.0/LGPLv3"
  gem.summary = %Q{Tengine Event API to access the queue}
  gem.description = %Q{Tengine Event API to access the queue}
  gem.email = "tengine-info@groovenauts.jp"
  gem.authors = %w[taigou totty g-morita shyouhei akm]
  gem.bindir = 'bin'
  gem.executables = ['tengine_fire', 'tengine_event_sucks']
  # dependencies defined in Gemfile
end
Jeweler::RubygemsDotOrgTasks.new

require 'rspec/core'
require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec) do |spec|
  spec.rspec_opts = %w'-f doc'
  spec.pattern = FileList['spec/**/*_spec.rb']
end

RSpec::Core::RakeTask.new(:rcov) do |spec|
  spec.pattern = 'spec/**/*_spec.rb'
  spec.rcov = true
end

task :default => :spec

require 'yard'
YARD::Rake::YardocTask.new

require 'ci/reporter/rake/rspec'

task :sucks do
  fp = File.expand_path '../bin/tengine_event_sucks', __FILE__
  load fp
end
