require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Tengine::Core::EventsController do

  # This should return the minimal set of attributes required to create a valid
  # Tengine::Core::Event. As you add validations to Tengine::Core::Event, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all tengine_core_events as @tengine_core_events" do
      Tengine::Core::Event.delete_all
      event = Tengine::Core::Event.create! valid_attributes
      event.level = 1
      get :index
      events = assigns(:events)
      events.to_a.should eq([event])
    end
  end

  describe "GET show" do
    it "assigns the requested event as @event" do
      event = Tengine::Core::Event.find_or_create_by valid_attributes
      get :show, :id => event.id.to_s
      assigns(:event).should eq(event)
    end
  end

  describe "GET new" do
    it "assigns a new event as @event" do
      get :new
      assigns(:event).should be_a_new(Tengine::Core::Event)
    end
  end

  describe "GET edit" do
    it "assigns the requested event as @event" do
      event = Tengine::Core::Event.find_or_create_by valid_attributes
      get :edit, :id => event.id.to_s
      assigns(:event).should eq(event)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      before do
        Tengine::Core::Event.delete_all
      end

      it "creates a new Tengine::Core::Event" do
        expect {
          post :create, :event => valid_attributes
        }.to change(Tengine::Core::Event, :count).by(1)
      end

      it "assigns a newly created event as @event" do
        post :create, :event => valid_attributes
        assigns(:event).should be_a(Tengine::Core::Event)
        assigns(:event).should be_persisted
      end

      it "redirects to the created event" do
        post :create, :event => valid_attributes
        response.should redirect_to(Tengine::Core::Event.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved event as @event" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Core::Event.any_instance.stub(:save).and_return(false)
        post :create, :event => {}
        assigns(:event).should be_a_new(Tengine::Core::Event)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Core::Event.any_instance.stub(:save).and_return(false)
        post :create, :event => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested event" do
        event = Tengine::Core::Event.find_or_create_by valid_attributes
        # Assuming there are no other tengine_core_events in the database, this
        # specifies that the Tengine::Core::Event created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tengine::Core::Event.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => event.id, :event => {'these' => 'params'}
      end

      it "assigns the requested event as @event" do
        event = Tengine::Core::Event.find_or_create_by valid_attributes
        put :update, :id => event.id, :event => valid_attributes
        assigns(:event).should eq(event)
      end

      it "redirects to the event" do
        event = Tengine::Core::Event.find_or_create_by valid_attributes
        put :update, :id => event.id, :event => valid_attributes
        response.should redirect_to(event)
      end
    end

    describe "with invalid params" do
      it "assigns the event as @event" do
        event = Tengine::Core::Event.find_or_create_by valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Core::Event.any_instance.stub(:save).and_return(false)
        put :update, :id => event.id.to_s, :event => {}
        assigns(:event).should eq(event)
      end

      it "re-renders the 'edit' template" do
        event = Tengine::Core::Event.find_or_create_by valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Core::Event.any_instance.stub(:save).and_return(false)
        put :update, :id => event.id.to_s, :event => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested event" do
      event = Tengine::Core::Event.find_or_create_by valid_attributes
      expect {
        delete :destroy, :id => event.id.to_s
      }.to change(Tengine::Core::Event, :count).by(-1)
    end

    it "redirects to the tengine_core_events list" do
      event = Tengine::Core::Event.find_or_create_by valid_attributes
      delete :destroy, :id => event.id.to_s
      response.should redirect_to(tengine_core_events_url)
    end
  end

end
