require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Tengine::Core::HandlersController do

  # This should return the minimal set of attributes required to create a valid
  # Tengine::Core::Handler. As you add validations to Tengine::Core::Handler, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all tengine_core_handlers as @tengine_core_handlers" do
      Tengine::Core::Handler.delete_all
      handler = Tengine::Core::Handler.create! valid_attributes
      get :index
      handlers = assigns(:handlers)
      handlers.to_a.should eq([handler])
    end
  end

  describe "GET show" do
    it "assigns the requested handler as @handler" do
      handler = Tengine::Core::Handler.create! valid_attributes
      get :show, :id => handler.id.to_s
      assigns(:handler).should eq(handler)
    end
  end

  describe "GET new" do
    it "assigns a new handler as @handler" do
      get :new
      assigns(:handler).should be_a_new(Tengine::Core::Handler)
    end
  end

  describe "GET edit" do
    it "assigns the requested handler as @handler" do
      handler = Tengine::Core::Handler.create! valid_attributes
      get :edit, :id => handler.id.to_s
      assigns(:handler).should eq(handler)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tengine::Core::Handler" do
        expect {
          post :create, :handler => valid_attributes
        }.to change(Tengine::Core::Handler, :count).by(1)
      end

      it "assigns a newly created handler as @handler" do
        post :create, :handler => valid_attributes
        assigns(:handler).should be_a(Tengine::Core::Handler)
        assigns(:handler).should be_persisted
      end

      it "redirects to the created handler" do
        post :create, :handler => valid_attributes
        response.should redirect_to(Tengine::Core::Handler.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved handler as @handler" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Core::Handler.any_instance.stub(:save).and_return(false)
        post :create, :handler => {}
        assigns(:handler).should be_a_new(Tengine::Core::Handler)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Core::Handler.any_instance.stub(:save).and_return(false)
        post :create, :handler => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested handler" do
        handler = Tengine::Core::Handler.create! valid_attributes
        # Assuming there are no other tengine_core_handlers in the database, this
        # specifies that the Tengine::Core::Handler created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tengine::Core::Handler.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => handler.id, :handler => {'these' => 'params'}
      end

      it "assigns the requested handler as @handler" do
        handler = Tengine::Core::Handler.create! valid_attributes
        put :update, :id => handler.id, :handler => valid_attributes
        assigns(:handler).should eq(handler)
      end

      it "redirects to the handler" do
        handler = Tengine::Core::Handler.create! valid_attributes
        put :update, :id => handler.id, :handler => valid_attributes
        response.should redirect_to(handler)
      end
    end

    describe "with invalid params" do
      it "assigns the handler as @handler" do
        handler = Tengine::Core::Handler.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Core::Handler.any_instance.stub(:save).and_return(false)
        put :update, :id => handler.id.to_s, :handler => {}
        assigns(:handler).should eq(handler)
      end

      it "re-renders the 'edit' template" do
        handler = Tengine::Core::Handler.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Core::Handler.any_instance.stub(:save).and_return(false)
        put :update, :id => handler.id.to_s, :handler => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested handler" do
      handler = Tengine::Core::Handler.create! valid_attributes
      expect {
        delete :destroy, :id => handler.id.to_s
      }.to change(Tengine::Core::Handler, :count).by(-1)
    end

    it "redirects to the tengine_core_handlers list" do
      handler = Tengine::Core::Handler.create! valid_attributes
      delete :destroy, :id => handler.id.to_s
      response.should redirect_to(tengine_core_handlers_url)
    end
  end

end
