require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Tengine::Core::HandlerPathsController do

  # This should return the minimal set of attributes required to create a valid
  # Tengine::Core::HandlerPath. As you add validations to Tengine::Core::HandlerPath, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all tengine_core_handler_paths as @tengine_core_handler_paths" do
      Tengine::Core::HandlerPath.delete_all
      handler_path = Tengine::Core::HandlerPath.create! valid_attributes
      get :index
      handler_paths = assigns(:handler_paths)
      handler_paths.to_a.should eq([handler_path])
    end
  end

  describe "GET show" do
    it "assigns the requested handler_path as @handler_path" do
      handler_path = Tengine::Core::HandlerPath.create! valid_attributes
      get :show, :id => handler_path.id.to_s
      assigns(:handler_path).should eq(handler_path)
    end
  end

  describe "GET new" do
    it "assigns a new handler_path as @handler_path" do
      get :new
      assigns(:handler_path).should be_a_new(Tengine::Core::HandlerPath)
    end
  end

  describe "GET edit" do
    it "assigns the requested handler_path as @handler_path" do
      handler_path = Tengine::Core::HandlerPath.create! valid_attributes
      get :edit, :id => handler_path.id.to_s
      assigns(:handler_path).should eq(handler_path)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tengine::Core::HandlerPath" do
        expect {
          post :create, :handler_path => valid_attributes
        }.to change(Tengine::Core::HandlerPath, :count).by(1)
      end

      it "assigns a newly created handler_path as @handler_path" do
        post :create, :handler_path => valid_attributes
        assigns(:handler_path).should be_a(Tengine::Core::HandlerPath)
        assigns(:handler_path).should be_persisted
      end

      it "redirects to the created handler_path" do
        post :create, :handler_path => valid_attributes
        response.should redirect_to(Tengine::Core::HandlerPath.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved handler_path as @handler_path" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Core::HandlerPath.any_instance.stub(:save).and_return(false)
        post :create, :handler_path => {}
        assigns(:handler_path).should be_a_new(Tengine::Core::HandlerPath)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Core::HandlerPath.any_instance.stub(:save).and_return(false)
        post :create, :handler_path => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested handler_path" do
        handler_path = Tengine::Core::HandlerPath.create! valid_attributes
        # Assuming there are no other tengine_core_handler_paths in the database, this
        # specifies that the Tengine::Core::HandlerPath created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tengine::Core::HandlerPath.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => handler_path.id, :handler_path => {'these' => 'params'}
      end

      it "assigns the requested handler_path as @handler_path" do
        handler_path = Tengine::Core::HandlerPath.create! valid_attributes
        put :update, :id => handler_path.id, :handler_path => valid_attributes
        assigns(:handler_path).should eq(handler_path)
      end

      it "redirects to the handler_path" do
        handler_path = Tengine::Core::HandlerPath.create! valid_attributes
        put :update, :id => handler_path.id, :handler_path => valid_attributes
        response.should redirect_to(handler_path)
      end
    end

    describe "with invalid params" do
      it "assigns the handler_path as @handler_path" do
        handler_path = Tengine::Core::HandlerPath.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Core::HandlerPath.any_instance.stub(:save).and_return(false)
        put :update, :id => handler_path.id.to_s, :handler_path => {}
        assigns(:handler_path).should eq(handler_path)
      end

      it "re-renders the 'edit' template" do
        handler_path = Tengine::Core::HandlerPath.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Core::HandlerPath.any_instance.stub(:save).and_return(false)
        put :update, :id => handler_path.id.to_s, :handler_path => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested handler_path" do
      handler_path = Tengine::Core::HandlerPath.create! valid_attributes
      expect {
        delete :destroy, :id => handler_path.id.to_s
      }.to change(Tengine::Core::HandlerPath, :count).by(-1)
    end

    it "redirects to the tengine_core_handler_paths list" do
      handler_path = Tengine::Core::HandlerPath.create! valid_attributes
      delete :destroy, :id => handler_path.id.to_s
      response.should redirect_to(tengine_core_handler_paths_url)
    end
  end

end
