require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Tengine::Core::DriversController do

  # This should return the minimal set of attributes required to create a valid
  # Tengine::Core::Driver. As you add validations to Tengine::Core::Driver, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      :name => "driver100",
      :version => "100",
    }
  end

  before do
    Tengine::Core::Driver.delete_all
  end

  describe "GET index" do
    it "assigns all tengine_core_drivers as @tengine_core_drivers" do
      Tengine::Core::Driver.delete_all
      driver = Tengine::Core::Driver.create! valid_attributes
      get :index
      drivers = assigns(:drivers)
      drivers.to_a.should eq([driver])
    end
  end

  describe "GET show" do
    it "assigns the requested driver as @driver" do
      driver = Tengine::Core::Driver.create! valid_attributes
      get :show, :id => driver.id.to_s
      assigns(:driver).should eq(driver)
    end
  end

  describe "GET new" do
    it "assigns a new driver as @driver" do
      get :new
      assigns(:driver).should be_a_new(Tengine::Core::Driver)
    end
  end

  describe "GET edit" do
    it "assigns the requested driver as @driver" do
      driver = Tengine::Core::Driver.create! valid_attributes
      get :edit, :id => driver.id.to_s
      assigns(:driver).should eq(driver)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tengine::Core::Driver" do
        expect {
          post :create, :driver => valid_attributes
        }.to change(Tengine::Core::Driver, :count).by(1)
      end

      it "assigns a newly created driver as @driver" do
        post :create, :driver => valid_attributes
        assigns(:driver).should be_a(Tengine::Core::Driver)
        assigns(:driver).should be_persisted
      end

      it "redirects to the created driver" do
        post :create, :driver => valid_attributes
        response.should redirect_to(Tengine::Core::Driver.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved driver as @driver" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Core::Driver.any_instance.stub(:save).and_return(false)
        post :create, :driver => {}
        assigns(:driver).should be_a_new(Tengine::Core::Driver)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Core::Driver.any_instance.stub(:save).and_return(false)
        post :create, :driver => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested driver" do
        driver = Tengine::Core::Driver.create! valid_attributes
        # Assuming there are no other tengine_core_drivers in the database, this
        # specifies that the Tengine::Core::Driver created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tengine::Core::Driver.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => driver.id, :driver => {'these' => 'params'}
      end

      it "assigns the requested driver as @driver" do
        driver = Tengine::Core::Driver.create! valid_attributes
        put :update, :id => driver.id, :driver => valid_attributes
        assigns(:driver).should eq(driver)
      end

      it "redirects to the driver" do
        driver = Tengine::Core::Driver.create! valid_attributes
        put :update, :id => driver.id, :driver => valid_attributes
        response.should redirect_to(driver)
      end
    end

    describe "with invalid params" do
      it "assigns the driver as @driver" do
        driver = Tengine::Core::Driver.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Core::Driver.any_instance.stub(:save).and_return(false)
        put :update, :id => driver.id.to_s, :driver => {}
        assigns(:driver).should eq(driver)
      end

      it "re-renders the 'edit' template" do
        driver = Tengine::Core::Driver.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Core::Driver.any_instance.stub(:save).and_return(false)
        put :update, :id => driver.id.to_s, :driver => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested driver" do
      driver = Tengine::Core::Driver.create! valid_attributes
      expect {
        delete :destroy, :id => driver.id.to_s
      }.to change(Tengine::Core::Driver, :count).by(-1)
    end

    it "redirects to the tengine_core_drivers list" do
      driver = Tengine::Core::Driver.create! valid_attributes
      delete :destroy, :id => driver.id.to_s
      response.should redirect_to(tengine_core_drivers_url)
    end
  end

end
