require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Tengine::Job::CategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # Tengine::Job::Category. As you add validations to Tengine::Job::Category, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all tengine_job_categories as @tengine_job_categories" do
      Tengine::Job::Category.delete_all
      category = Tengine::Job::Category.create! valid_attributes
      get :index
      categories = assigns(:categories)
      categories.to_a.should eq([category])
    end
  end

  describe "GET show" do
    it "assigns the requested category as @category" do
      category = Tengine::Job::Category.create! valid_attributes
      get :show, :id => category.id.to_s
      assigns(:category).should eq(category)
    end
  end

  describe "GET new" do
    it "assigns a new category as @category" do
      get :new
      assigns(:category).should be_a_new(Tengine::Job::Category)
    end
  end

  describe "GET edit" do
    it "assigns the requested category as @category" do
      category = Tengine::Job::Category.create! valid_attributes
      get :edit, :id => category.id.to_s
      assigns(:category).should eq(category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tengine::Job::Category" do
        expect {
          post :create, :category => valid_attributes
        }.to change(Tengine::Job::Category, :count).by(1)
      end

      it "assigns a newly created category as @category" do
        post :create, :category => valid_attributes
        assigns(:category).should be_a(Tengine::Job::Category)
        assigns(:category).should be_persisted
      end

      it "redirects to the created category" do
        post :create, :category => valid_attributes
        response.should redirect_to(Tengine::Job::Category.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved category as @category" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::Category.any_instance.stub(:save).and_return(false)
        post :create, :category => {}
        assigns(:category).should be_a_new(Tengine::Job::Category)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::Category.any_instance.stub(:save).and_return(false)
        post :create, :category => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested category" do
        category = Tengine::Job::Category.create! valid_attributes
        # Assuming there are no other tengine_job_categories in the database, this
        # specifies that the Tengine::Job::Category created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tengine::Job::Category.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => category.id, :category => {'these' => 'params'}
      end

      it "assigns the requested category as @category" do
        category = Tengine::Job::Category.create! valid_attributes
        put :update, :id => category.id, :category => valid_attributes
        assigns(:category).should eq(category)
      end

      it "redirects to the category" do
        category = Tengine::Job::Category.create! valid_attributes
        put :update, :id => category.id, :category => valid_attributes
        response.should redirect_to(category)
      end
    end

    describe "with invalid params" do
      it "assigns the category as @category" do
        category = Tengine::Job::Category.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::Category.any_instance.stub(:save).and_return(false)
        put :update, :id => category.id.to_s, :category => {}
        assigns(:category).should eq(category)
      end

      it "re-renders the 'edit' template" do
        category = Tengine::Job::Category.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::Category.any_instance.stub(:save).and_return(false)
        put :update, :id => category.id.to_s, :category => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested category" do
      category = Tengine::Job::Category.create! valid_attributes
      expect {
        delete :destroy, :id => category.id.to_s
      }.to change(Tengine::Job::Category, :count).by(-1)
    end

    it "redirects to the tengine_job_categories list" do
      category = Tengine::Job::Category.create! valid_attributes
      delete :destroy, :id => category.id.to_s
      response.should redirect_to(tengine_job_categories_url)
    end
  end

end
