require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Tengine::Job::ExpansionsController do

  # This should return the minimal set of attributes required to create a valid
  # Tengine::Job::Expansion. As you add validations to Tengine::Job::Expansion, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:name => "test1"}
  end

  describe "GET index" do
    it "assigns all tengine_job_expansions as @tengine_job_expansions" do
      Tengine::Job::Expansion.delete_all
      expansion = Tengine::Job::Expansion.create! valid_attributes
      get :index
      expansions = assigns(:expansions)
      expansions.to_a.should eq([expansion])
    end
  end

  describe "GET show" do
    it "assigns the requested expansion as @expansion" do
      expansion = Tengine::Job::Expansion.create! valid_attributes
      get :show, :id => expansion.id.to_s
      assigns(:expansion).should eq(expansion)
    end
  end

  describe "GET new" do
    it "assigns a new expansion as @expansion" do
      get :new
      assigns(:expansion).should be_a_new(Tengine::Job::Expansion)
    end
  end

  describe "GET edit" do
    it "assigns the requested expansion as @expansion" do
      expansion = Tengine::Job::Expansion.create! valid_attributes
      get :edit, :id => expansion.id.to_s
      assigns(:expansion).should eq(expansion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tengine::Job::Expansion" do
        expect {
          post :create, :expansion => valid_attributes
        }.to change(Tengine::Job::Expansion, :count).by(1)
      end

      it "assigns a newly created expansion as @expansion" do
        post :create, :expansion => valid_attributes
        assigns(:expansion).should be_a(Tengine::Job::Expansion)
        assigns(:expansion).should be_persisted
      end

      it "redirects to the created expansion" do
        post :create, :expansion => valid_attributes
        response.should redirect_to(Tengine::Job::Expansion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved expansion as @expansion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::Expansion.any_instance.stub(:save).and_return(false)
        post :create, :expansion => {}
        assigns(:expansion).should be_a_new(Tengine::Job::Expansion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::Expansion.any_instance.stub(:save).and_return(false)
        post :create, :expansion => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested expansion" do
        expansion = Tengine::Job::Expansion.create! valid_attributes
        # Assuming there are no other tengine_job_expansions in the database, this
        # specifies that the Tengine::Job::Expansion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tengine::Job::Expansion.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => expansion.id, :expansion => {'these' => 'params'}
      end

      it "assigns the requested expansion as @expansion" do
        expansion = Tengine::Job::Expansion.create! valid_attributes
        put :update, :id => expansion.id, :expansion => valid_attributes
        assigns(:expansion).should eq(expansion)
      end

      it "redirects to the expansion" do
        expansion = Tengine::Job::Expansion.create! valid_attributes
        put :update, :id => expansion.id, :expansion => valid_attributes
        response.should redirect_to(expansion)
      end
    end

    describe "with invalid params" do
      it "assigns the expansion as @expansion" do
        expansion = Tengine::Job::Expansion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::Expansion.any_instance.stub(:save).and_return(false)
        put :update, :id => expansion.id.to_s, :expansion => {}
        assigns(:expansion).should eq(expansion)
      end

      it "re-renders the 'edit' template" do
        expansion = Tengine::Job::Expansion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::Expansion.any_instance.stub(:save).and_return(false)
        put :update, :id => expansion.id.to_s, :expansion => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested expansion" do
      expansion = Tengine::Job::Expansion.create! valid_attributes
      expect {
        delete :destroy, :id => expansion.id.to_s
      }.to change(Tengine::Job::Expansion, :count).by(-1)
    end

    it "redirects to the tengine_job_expansions list" do
      expansion = Tengine::Job::Expansion.create! valid_attributes
      delete :destroy, :id => expansion.id.to_s
      response.should redirect_to(tengine_job_expansions_url)
    end
  end

end
