require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Tengine::Job::JobnetsController do

  # This should return the minimal set of attributes required to create a valid
  # Tengine::Job::Jobnet. As you add validations to Tengine::Job::Jobnet, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:name => "test1"}
  end

  describe "GET index" do
    it "assigns all tengine_job_jobnets as @tengine_job_jobnets" do
      Tengine::Job::Vertex.delete_all
      jobnet = Tengine::Job::Jobnet.create! valid_attributes
      get :index
      jobnets = assigns(:jobnets)
      jobnets.to_a.should eq([jobnet])
    end
  end

  describe "GET show" do
    it "assigns the requested jobnet as @jobnet" do
      jobnet = Tengine::Job::Jobnet.create! valid_attributes
      get :show, :id => jobnet.id.to_s
      assigns(:jobnet).should eq(jobnet)
    end
  end

  describe "GET new" do
    it "assigns a new jobnet as @jobnet" do
      get :new
      assigns(:jobnet).should be_a_new(Tengine::Job::Jobnet)
    end
  end

  describe "GET edit" do
    it "assigns the requested jobnet as @jobnet" do
      jobnet = Tengine::Job::Jobnet.create! valid_attributes
      get :edit, :id => jobnet.id.to_s
      assigns(:jobnet).should eq(jobnet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tengine::Job::Jobnet" do
        expect {
          post :create, :jobnet => valid_attributes
        }.to change(Tengine::Job::Jobnet, :count).by(1)
      end

      it "assigns a newly created jobnet as @jobnet" do
        post :create, :jobnet => valid_attributes
        assigns(:jobnet).should be_a(Tengine::Job::Jobnet)
        assigns(:jobnet).should be_persisted
      end

      it "redirects to the created jobnet" do
        post :create, :jobnet => valid_attributes
        response.should redirect_to(Tengine::Job::Jobnet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved jobnet as @jobnet" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::Jobnet.any_instance.stub(:save).and_return(false)
        post :create, :jobnet => {}
        assigns(:jobnet).should be_a_new(Tengine::Job::Jobnet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::Jobnet.any_instance.stub(:save).and_return(false)
        post :create, :jobnet => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested jobnet" do
        jobnet = Tengine::Job::Jobnet.create! valid_attributes
        # Assuming there are no other tengine_job_jobnets in the database, this
        # specifies that the Tengine::Job::Jobnet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tengine::Job::Jobnet.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => jobnet.id, :jobnet => {'these' => 'params'}
      end

      it "assigns the requested jobnet as @jobnet" do
        jobnet = Tengine::Job::Jobnet.create! valid_attributes
        put :update, :id => jobnet.id, :jobnet => valid_attributes
        assigns(:jobnet).should eq(jobnet)
      end

      it "redirects to the jobnet" do
        jobnet = Tengine::Job::Jobnet.create! valid_attributes
        put :update, :id => jobnet.id, :jobnet => valid_attributes
        response.should redirect_to(jobnet)
      end
    end

    describe "with invalid params" do
      it "assigns the jobnet as @jobnet" do
        jobnet = Tengine::Job::Jobnet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::Jobnet.any_instance.stub(:save).and_return(false)
        put :update, :id => jobnet.id.to_s, :jobnet => {}
        assigns(:jobnet).should eq(jobnet)
      end

      it "re-renders the 'edit' template" do
        jobnet = Tengine::Job::Jobnet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::Jobnet.any_instance.stub(:save).and_return(false)
        put :update, :id => jobnet.id.to_s, :jobnet => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested jobnet" do
      jobnet = Tengine::Job::Jobnet.create! valid_attributes
      expect {
        delete :destroy, :id => jobnet.id.to_s
      }.to change(Tengine::Job::Jobnet, :count).by(-1)
    end

    it "redirects to the tengine_job_jobnets list" do
      jobnet = Tengine::Job::Jobnet.create! valid_attributes
      delete :destroy, :id => jobnet.id.to_s
      response.should redirect_to(tengine_job_jobnets_url)
    end
  end

end
