# # -*- coding: utf-8 -*-

require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Tengine::Resource::PhysicalServersController do

  # This should return the minimal set of attributes required to create a valid
  # Tengine::Resource::PhysicalServer. As you add validations to Tengine::Resource::PhysicalServer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      :name => "physical_server1"
    }
  end

  before do
    Tengine::Resource::PhysicalServer.delete_all
  end

  describe "GET index" do
    it "assigns all tengine_resource_physical_servers as @tengine_resource_physical_servers" do
      Tengine::Resource::PhysicalServer.delete_all
      physical_server = Tengine::Resource::PhysicalServer.create! valid_attributes
      get :index
      physical_servers = assigns(:physical_servers)
      physical_servers.to_a.should eq([physical_server])
    end
  end

  describe "GET show" do
    it "assigns the requested physical_server as @physical_server" do
      physical_server = Tengine::Resource::PhysicalServer.create! valid_attributes
      get :show, :id => physical_server.id.to_s
      response.should redirect_to(:action => "index")
    end
  end

  # controlerのnewメソッドと同様にコメントしています。
  # describe "GET new" do
  #   it "assigns a new physical_server as @physical_server" do
  #     get :new
  #     assigns(:physical_server).should be_a_new(Tengine::Resource::PhysicalServer)
  #   end
  # end

  describe "GET edit" do
    it "assigns the requested physical_server as @physical_server" do
      physical_server = Tengine::Resource::PhysicalServer.create! valid_attributes
      get :edit, :id => physical_server.id.to_s
      assigns(:physical_server).should eq(physical_server)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tengine::Resource::PhysicalServer" do
        expect {
          post :create, :physical_server => valid_attributes
        }.to change(Tengine::Resource::PhysicalServer, :count).by(1)
      end

      it "assigns a newly created physical_server as @physical_server" do
        post :create, :physical_server => valid_attributes
        assigns(:physical_server).should be_a(Tengine::Resource::PhysicalServer)
        assigns(:physical_server).should be_persisted
      end

      it "redirects to the created physical_server" do
        post :create, :physical_server => valid_attributes
        response.should redirect_to(Tengine::Resource::PhysicalServer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved physical_server as @physical_server" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Resource::PhysicalServer.any_instance.stub(:save).and_return(false)
        post :create, :physical_server => {}
        assigns(:physical_server).should be_a_new(Tengine::Resource::PhysicalServer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Resource::PhysicalServer.any_instance.stub(:save).and_return(false)
        post :create, :physical_server => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested physical_server" do
        physical_server = Tengine::Resource::PhysicalServer.create! valid_attributes
        # Assuming there are no other tengine_resource_physical_servers in the database, this
        # specifies that the Tengine::Resource::PhysicalServer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tengine::Resource::PhysicalServer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => physical_server.id, :physical_server => {'these' => 'params'}
      end

      it "assigns the requested physical_server as @physical_server" do
        physical_server = Tengine::Resource::PhysicalServer.create! valid_attributes
        put :update, :id => physical_server.id, :physical_server => valid_attributes
        assigns(:physical_server).should eq(physical_server)
      end

      it "redirects to the physical_server" do
        physical_server = Tengine::Resource::PhysicalServer.create! valid_attributes
        put :update, :id => physical_server.id, :physical_server => valid_attributes
        response.should redirect_to(physical_server)
      end
    end

    describe "with invalid params" do
      it "assigns the physical_server as @physical_server" do
        physical_server = Tengine::Resource::PhysicalServer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Resource::PhysicalServer.any_instance.stub(:save).and_return(false)
        put :update, :id => physical_server.id.to_s, :physical_server => {}
        assigns(:physical_server).should eq(physical_server)
      end

      it "re-renders the 'edit' template" do
        physical_server = Tengine::Resource::PhysicalServer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Resource::PhysicalServer.any_instance.stub(:save).and_return(false)
        put :update, :id => physical_server.id.to_s, :physical_server => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested physical_server" do
      physical_server = Tengine::Resource::PhysicalServer.create! valid_attributes
      expect {
        delete :destroy, :id => physical_server.id.to_s
      }.to change(Tengine::Resource::PhysicalServer, :count).by(-1)
    end

    it "redirects to the tengine_resource_physical_servers list" do
      physical_server = Tengine::Resource::PhysicalServer.create! valid_attributes
      delete :destroy, :id => physical_server.id.to_s
      response.should redirect_to(tengine_resource_physical_servers_url)
    end
  end

end
