require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Tengine::Resource::ProvidersController do

  # This should return the minimal set of attributes required to create a valid
  # Tengine::Resource::Provider. As you add validations to Tengine::Resource::Provider, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      :name => "provider1"
    }
  end

  describe "GET index" do
    it "assigns all tengine_resource_providers as @tengine_resource_providers" do
      Tengine::Resource::Provider.delete_all
      provider = Tengine::Resource::Provider.create! valid_attributes
      get :index
      providers = assigns(:providers)
      providers.to_a.should eq([provider])
    end
  end

  describe "GET show" do
    it "assigns the requested provider as @provider" do
      provider = Tengine::Resource::Provider.create! valid_attributes
      get :show, :id => provider.id.to_s
      assigns(:provider).should eq(provider)
    end
  end

  describe "GET new" do
    it "assigns a new provider as @provider" do
      get :new
      assigns(:provider).should be_a_new(Tengine::Resource::Provider)
    end
  end

  describe "GET edit" do
    it "assigns the requested provider as @provider" do
      provider = Tengine::Resource::Provider.create! valid_attributes
      get :edit, :id => provider.id.to_s
      assigns(:provider).should eq(provider)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tengine::Resource::Provider" do
        expect {
          post :create, :provider => valid_attributes
        }.to change(Tengine::Resource::Provider, :count).by(1)
      end

      it "assigns a newly created provider as @provider" do
        post :create, :provider => valid_attributes
        assigns(:provider).should be_a(Tengine::Resource::Provider)
        assigns(:provider).should be_persisted
      end

      it "redirects to the created provider" do
        post :create, :provider => valid_attributes
        response.should redirect_to(Tengine::Resource::Provider.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved provider as @provider" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Resource::Provider.any_instance.stub(:save).and_return(false)
        post :create, :provider => {}
        assigns(:provider).should be_a_new(Tengine::Resource::Provider)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Resource::Provider.any_instance.stub(:save).and_return(false)
        post :create, :provider => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested provider" do
        provider = Tengine::Resource::Provider.create! valid_attributes
        # Assuming there are no other tengine_resource_providers in the database, this
        # specifies that the Tengine::Resource::Provider created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tengine::Resource::Provider.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => provider.id, :provider => {'these' => 'params'}
      end

      it "assigns the requested provider as @provider" do
        provider = Tengine::Resource::Provider.create! valid_attributes
        put :update, :id => provider.id, :provider => valid_attributes
        assigns(:provider).should eq(provider)
      end

      it "redirects to the provider" do
        provider = Tengine::Resource::Provider.create! valid_attributes
        put :update, :id => provider.id, :provider => valid_attributes
        response.should redirect_to(provider)
      end
    end

    describe "with invalid params" do
      it "assigns the provider as @provider" do
        provider = Tengine::Resource::Provider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Resource::Provider.any_instance.stub(:save).and_return(false)
        put :update, :id => provider.id.to_s, :provider => {}
        assigns(:provider).should eq(provider)
      end

      it "re-renders the 'edit' template" do
        provider = Tengine::Resource::Provider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Resource::Provider.any_instance.stub(:save).and_return(false)
        put :update, :id => provider.id.to_s, :provider => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested provider" do
      provider = Tengine::Resource::Provider.create! valid_attributes
      expect {
        delete :destroy, :id => provider.id.to_s
      }.to change(Tengine::Resource::Provider, :count).by(-1)
    end

    it "redirects to the tengine_resource_providers list" do
      provider = Tengine::Resource::Provider.create! valid_attributes
      delete :destroy, :id => provider.id.to_s
      response.should redirect_to(tengine_resource_providers_url)
    end
  end

end
