require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Tengine::Resource::VirtualServerTypesController do

  # This should return the minimal set of attributes required to create a valid
  # Tengine::Resource::VirtualServerType. As you add validations to Tengine::Resource::VirtualServerType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all tengine_resource_virtual_server_types as @tengine_resource_virtual_server_types" do
      Tengine::Resource::VirtualServerType.delete_all
      virtual_server_type = Tengine::Resource::VirtualServerType.create! valid_attributes
      get :index
      virtual_server_types = assigns(:virtual_server_types)
      virtual_server_types.to_a.should eq([virtual_server_type])
    end
  end

  describe "GET show" do
    it "assigns the requested virtual_server_type as @virtual_server_type" do
      virtual_server_type = Tengine::Resource::VirtualServerType.create! valid_attributes
      get :show, :id => virtual_server_type.id.to_s
      assigns(:virtual_server_type).should eq(virtual_server_type)
    end
  end

  describe "GET new" do
    it "assigns a new virtual_server_type as @virtual_server_type" do
      get :new
      assigns(:virtual_server_type).should be_a_new(Tengine::Resource::VirtualServerType)
    end
  end

  describe "GET edit" do
    it "assigns the requested virtual_server_type as @virtual_server_type" do
      virtual_server_type = Tengine::Resource::VirtualServerType.create! valid_attributes
      get :edit, :id => virtual_server_type.id.to_s
      assigns(:virtual_server_type).should eq(virtual_server_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tengine::Resource::VirtualServerType" do
        expect {
          post :create, :virtual_server_type => valid_attributes
        }.to change(Tengine::Resource::VirtualServerType, :count).by(1)
      end

      it "assigns a newly created virtual_server_type as @virtual_server_type" do
        post :create, :virtual_server_type => valid_attributes
        assigns(:virtual_server_type).should be_a(Tengine::Resource::VirtualServerType)
        assigns(:virtual_server_type).should be_persisted
      end

      it "redirects to the created virtual_server_type" do
        post :create, :virtual_server_type => valid_attributes
        response.should redirect_to(Tengine::Resource::VirtualServerType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved virtual_server_type as @virtual_server_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Resource::VirtualServerType.any_instance.stub(:save).and_return(false)
        post :create, :virtual_server_type => {}
        assigns(:virtual_server_type).should be_a_new(Tengine::Resource::VirtualServerType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Resource::VirtualServerType.any_instance.stub(:save).and_return(false)
        post :create, :virtual_server_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested virtual_server_type" do
        virtual_server_type = Tengine::Resource::VirtualServerType.create! valid_attributes
        # Assuming there are no other tengine_resource_virtual_server_types in the database, this
        # specifies that the Tengine::Resource::VirtualServerType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tengine::Resource::VirtualServerType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => virtual_server_type.id, :virtual_server_type => {'these' => 'params'}
      end

      it "assigns the requested virtual_server_type as @virtual_server_type" do
        virtual_server_type = Tengine::Resource::VirtualServerType.create! valid_attributes
        put :update, :id => virtual_server_type.id, :virtual_server_type => valid_attributes
        assigns(:virtual_server_type).should eq(virtual_server_type)
      end

      it "redirects to the virtual_server_type" do
        virtual_server_type = Tengine::Resource::VirtualServerType.create! valid_attributes
        put :update, :id => virtual_server_type.id, :virtual_server_type => valid_attributes
        response.should redirect_to(virtual_server_type)
      end
    end

    describe "with invalid params" do
      it "assigns the virtual_server_type as @virtual_server_type" do
        virtual_server_type = Tengine::Resource::VirtualServerType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Resource::VirtualServerType.any_instance.stub(:save).and_return(false)
        put :update, :id => virtual_server_type.id.to_s, :virtual_server_type => {}
        assigns(:virtual_server_type).should eq(virtual_server_type)
      end

      it "re-renders the 'edit' template" do
        virtual_server_type = Tengine::Resource::VirtualServerType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Resource::VirtualServerType.any_instance.stub(:save).and_return(false)
        put :update, :id => virtual_server_type.id.to_s, :virtual_server_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested virtual_server_type" do
      virtual_server_type = Tengine::Resource::VirtualServerType.create! valid_attributes
      expect {
        delete :destroy, :id => virtual_server_type.id.to_s
      }.to change(Tengine::Resource::VirtualServerType, :count).by(-1)
    end

    it "redirects to the tengine_resource_virtual_server_types list" do
      virtual_server_type = Tengine::Resource::VirtualServerType.create! valid_attributes
      delete :destroy, :id => virtual_server_type.id.to_s
      response.should redirect_to(tengine_resource_virtual_server_types_url)
    end
  end

end
