require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Tengine::Job::ExecutionsController do

  # This should return the minimal set of attributes required to create a valid
  # Tengine::Job::Execution. As you add validations to Tengine::Job::Execution, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all tengine_job_executions as @tengine_job_executions" do
      Tengine::Job::Execution.delete_all
      execution = Tengine::Job::Execution.create! valid_attributes
      get :index
      executions = assigns(:executions)
      executions.to_a.should eq([execution])
    end
  end

  describe "GET show" do
    it "assigns the requested execution as @execution" do
      execution = Tengine::Job::Execution.create! valid_attributes
      get :show, :id => execution.id.to_s
      assigns(:execution).should eq(execution)
    end
  end

  describe "GET new" do
    it "assigns a new execution as @execution" do
      get :new
      assigns(:execution).should be_a_new(Tengine::Job::Execution)
    end
  end

  describe "GET edit" do
    it "assigns the requested execution as @execution" do
      execution = Tengine::Job::Execution.create! valid_attributes
      get :edit, :id => execution.id.to_s
      assigns(:execution).should eq(execution)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tengine::Job::Execution" do
        expect {
          post :create, :execution => valid_attributes
        }.to change(Tengine::Job::Execution, :count).by(1)
      end

      it "assigns a newly created execution as @execution" do
        post :create, :execution => valid_attributes
        assigns(:execution).should be_a(Tengine::Job::Execution)
        assigns(:execution).should be_persisted
      end

      it "redirects to the created execution" do
        post :create, :execution => valid_attributes
        response.should redirect_to(Tengine::Job::Execution.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved execution as @execution" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::Execution.any_instance.stub(:save).and_return(false)
        post :create, :execution => {}
        assigns(:execution).should be_a_new(Tengine::Job::Execution)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::Execution.any_instance.stub(:save).and_return(false)
        post :create, :execution => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested execution" do
        execution = Tengine::Job::Execution.create! valid_attributes
        # Assuming there are no other tengine_job_executions in the database, this
        # specifies that the Tengine::Job::Execution created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tengine::Job::Execution.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => execution.id, :execution => {'these' => 'params'}
      end

      it "assigns the requested execution as @execution" do
        execution = Tengine::Job::Execution.create! valid_attributes
        put :update, :id => execution.id, :execution => valid_attributes
        assigns(:execution).should eq(execution)
      end

      it "redirects to the execution" do
        execution = Tengine::Job::Execution.create! valid_attributes
        put :update, :id => execution.id, :execution => valid_attributes
        response.should redirect_to(execution)
      end
    end

    describe "with invalid params" do
      it "assigns the execution as @execution" do
        execution = Tengine::Job::Execution.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::Execution.any_instance.stub(:save).and_return(false)
        put :update, :id => execution.id.to_s, :execution => {}
        assigns(:execution).should eq(execution)
      end

      it "re-renders the 'edit' template" do
        execution = Tengine::Job::Execution.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::Execution.any_instance.stub(:save).and_return(false)
        put :update, :id => execution.id.to_s, :execution => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested execution" do
      execution = Tengine::Job::Execution.create! valid_attributes
      expect {
        delete :destroy, :id => execution.id.to_s
      }.to change(Tengine::Job::Execution, :count).by(-1)
    end

    it "redirects to the tengine_job_executions list" do
      execution = Tengine::Job::Execution.create! valid_attributes
      delete :destroy, :id => execution.id.to_s
      response.should redirect_to(tengine_job_executions_url)
    end
  end

end
