# -*- coding: utf-8 -*-
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Tengine::Job::JobnetActualsController do

  # This should return the minimal set of attributes required to create a valid
  # Tengine::Job::JobnetActual. As you add validations to Tengine::Job::JobnetActual, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:name => "test1"}
  end

  describe "GET index" do
    it "assigns all tengine_job_jobnet_actuals as @tengine_job_jobnet_actuals" do
      Tengine::Job::JobnetActual.delete_all

      # Tengine::Job::JobnetActual.delete_allでは、Tengine::Job::RootJobnetActual のデータまで消してくれないので、
      # Tengine::Job::RootJobnetActual.delete_allで削除します。
      Tengine::Job::RootJobnetActual.delete_all

      jobnet_actual = Tengine::Job::JobnetActual.create! valid_attributes
      get :index
      jobnet_actuals = assigns(:jobnet_actuals)
      jobnet_actuals.to_a.should eq([jobnet_actual])
    end
  end

  describe "GET show" do
    it "assigns the requested jobnet_actual as @jobnet_actual" do
      jobnet_actual = Tengine::Job::JobnetActual.create! valid_attributes
      get :show, :id => jobnet_actual.id.to_s
      assigns(:jobnet_actual).should eq(jobnet_actual)
    end
  end

  describe "GET new" do
    it "assigns a new jobnet_actual as @jobnet_actual" do
      get :new
      assigns(:jobnet_actual).should be_a_new(Tengine::Job::JobnetActual)
    end
  end

  describe "GET edit" do
    it "assigns the requested jobnet_actual as @jobnet_actual" do
      jobnet_actual = Tengine::Job::JobnetActual.create! valid_attributes
      get :edit, :id => jobnet_actual.id.to_s
      assigns(:jobnet_actual).should eq(jobnet_actual)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tengine::Job::JobnetActual" do
        expect {
          post :create, :jobnet_actual => valid_attributes
        }.to change(Tengine::Job::JobnetActual, :count).by(1)
      end

      it "assigns a newly created jobnet_actual as @jobnet_actual" do
        post :create, :jobnet_actual => valid_attributes
        assigns(:jobnet_actual).should be_a(Tengine::Job::JobnetActual)
        assigns(:jobnet_actual).should be_persisted
      end

      it "redirects to the created jobnet_actual" do
        post :create, :jobnet_actual => valid_attributes
        response.should redirect_to(Tengine::Job::JobnetActual.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved jobnet_actual as @jobnet_actual" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::JobnetActual.any_instance.stub(:save).and_return(false)
        post :create, :jobnet_actual => {}
        assigns(:jobnet_actual).should be_a_new(Tengine::Job::JobnetActual)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::JobnetActual.any_instance.stub(:save).and_return(false)
        post :create, :jobnet_actual => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested jobnet_actual" do
        jobnet_actual = Tengine::Job::JobnetActual.create! valid_attributes
        # Assuming there are no other tengine_job_jobnet_actuals in the database, this
        # specifies that the Tengine::Job::JobnetActual created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tengine::Job::JobnetActual.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => jobnet_actual.id, :jobnet_actual => {'these' => 'params'}
      end

      it "assigns the requested jobnet_actual as @jobnet_actual" do
        jobnet_actual = Tengine::Job::JobnetActual.create! valid_attributes
        put :update, :id => jobnet_actual.id, :jobnet_actual => valid_attributes
        assigns(:jobnet_actual).should eq(jobnet_actual)
      end

      it "redirects to the root_jobnet_actual show" do
        jobnet_actual = Tengine::Job::JobnetActual.create! valid_attributes
        put :update, :id => jobnet_actual.id, :jobnet_actual => valid_attributes
        response.should redirect_to(tengine_job_jobnet_actual_path(jobnet_actual))
      end
    end

    describe "with invalid params" do
      it "assigns the jobnet_actual as @jobnet_actual" do
        jobnet_actual = Tengine::Job::JobnetActual.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::JobnetActual.any_instance.stub(:save).and_return(false)
        put :update, :id => jobnet_actual.id.to_s, :jobnet_actual => {}
        assigns(:jobnet_actual).should eq(jobnet_actual)
      end

      it "re-renders the 'edit' template" do
        jobnet_actual = Tengine::Job::JobnetActual.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::JobnetActual.any_instance.stub(:save).and_return(false)
        put :update, :id => jobnet_actual.id.to_s, :jobnet_actual => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested jobnet_actual" do
      jobnet_actual = Tengine::Job::JobnetActual.create! valid_attributes
      expect {
        delete :destroy, :id => jobnet_actual.id.to_s
      }.to change(Tengine::Job::JobnetActual, :count).by(-1)
    end

    it "redirects to the tengine_job_jobnet_actuals list" do
      jobnet_actual = Tengine::Job::JobnetActual.create! valid_attributes
      delete :destroy, :id => jobnet_actual.id.to_s
      response.should redirect_to(tengine_job_jobnet_actuals_url)
    end
  end

end
