require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Tengine::Job::JobnetTemplatesController do

  # This should return the minimal set of attributes required to create a valid
  # Tengine::Job::JobnetTemplate. As you add validations to Tengine::Job::JobnetTemplate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all tengine_job_jobnet_templates as @tengine_job_jobnet_templates" do
      Tengine::Job::JobnetTemplate.delete_all
      jobnet_template = Tengine::Job::JobnetTemplate.create! valid_attributes
      get :index
      jobnet_templates = assigns(:jobnet_templates)
      jobnet_templates.to_a.should eq([jobnet_template])
    end
  end

  describe "GET show" do
    it "assigns the requested jobnet_template as @jobnet_template" do
      jobnet_template = Tengine::Job::JobnetTemplate.create! valid_attributes
      get :show, :id => jobnet_template.id.to_s
      assigns(:jobnet_template).should eq(jobnet_template)
    end
  end

  describe "GET new" do
    it "assigns a new jobnet_template as @jobnet_template" do
      get :new
      assigns(:jobnet_template).should be_a_new(Tengine::Job::JobnetTemplate)
    end
  end

  describe "GET edit" do
    it "assigns the requested jobnet_template as @jobnet_template" do
      jobnet_template = Tengine::Job::JobnetTemplate.create! valid_attributes
      get :edit, :id => jobnet_template.id.to_s
      assigns(:jobnet_template).should eq(jobnet_template)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tengine::Job::JobnetTemplate" do
        expect {
          post :create, :jobnet_template => valid_attributes
        }.to change(Tengine::Job::JobnetTemplate, :count).by(1)
      end

      it "assigns a newly created jobnet_template as @jobnet_template" do
        post :create, :jobnet_template => valid_attributes
        assigns(:jobnet_template).should be_a(Tengine::Job::JobnetTemplate)
        assigns(:jobnet_template).should be_persisted
      end

      it "redirects to the created jobnet_template" do
        post :create, :jobnet_template => valid_attributes
        response.should redirect_to(Tengine::Job::JobnetTemplate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved jobnet_template as @jobnet_template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::JobnetTemplate.any_instance.stub(:save).and_return(false)
        post :create, :jobnet_template => {}
        assigns(:jobnet_template).should be_a_new(Tengine::Job::JobnetTemplate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::JobnetTemplate.any_instance.stub(:save).and_return(false)
        post :create, :jobnet_template => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested jobnet_template" do
        jobnet_template = Tengine::Job::JobnetTemplate.create! valid_attributes
        # Assuming there are no other tengine_job_jobnet_templates in the database, this
        # specifies that the Tengine::Job::JobnetTemplate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tengine::Job::JobnetTemplate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => jobnet_template.id, :jobnet_template => {'these' => 'params'}
      end

      it "assigns the requested jobnet_template as @jobnet_template" do
        jobnet_template = Tengine::Job::JobnetTemplate.create! valid_attributes
        put :update, :id => jobnet_template.id, :jobnet_template => valid_attributes
        assigns(:jobnet_template).should eq(jobnet_template)
      end

      it "redirects to the jobnet_template" do
        jobnet_template = Tengine::Job::JobnetTemplate.create! valid_attributes
        put :update, :id => jobnet_template.id, :jobnet_template => valid_attributes
        response.should redirect_to(jobnet_template)
      end
    end

    describe "with invalid params" do
      it "assigns the jobnet_template as @jobnet_template" do
        jobnet_template = Tengine::Job::JobnetTemplate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::JobnetTemplate.any_instance.stub(:save).and_return(false)
        put :update, :id => jobnet_template.id.to_s, :jobnet_template => {}
        assigns(:jobnet_template).should eq(jobnet_template)
      end

      it "re-renders the 'edit' template" do
        jobnet_template = Tengine::Job::JobnetTemplate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::JobnetTemplate.any_instance.stub(:save).and_return(false)
        put :update, :id => jobnet_template.id.to_s, :jobnet_template => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested jobnet_template" do
      jobnet_template = Tengine::Job::JobnetTemplate.create! valid_attributes
      expect {
        delete :destroy, :id => jobnet_template.id.to_s
      }.to change(Tengine::Job::JobnetTemplate, :count).by(-1)
    end

    it "redirects to the tengine_job_jobnet_templates list" do
      jobnet_template = Tengine::Job::JobnetTemplate.create! valid_attributes
      delete :destroy, :id => jobnet_template.id.to_s
      response.should redirect_to(tengine_job_jobnet_templates_url)
    end
  end

end
