require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Tengine::Job::RootJobnetActualsController do

  # This should return the minimal set of attributes required to create a valid
  # Tengine::Job::RootJobnetActual. As you add validations to Tengine::Job::RootJobnetActual, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all tengine_job_root_jobnet_actuals as @tengine_job_root_jobnet_actuals" do
      Tengine::Job::RootJobnetActual.delete_all
      root_jobnet_actual = Tengine::Job::RootJobnetActual.create! valid_attributes
      get :index
      root_jobnet_actuals = assigns(:root_jobnet_actuals)
      root_jobnet_actuals.to_a.should eq([root_jobnet_actual])
    end
  end

  describe "GET show" do
    it "assigns the requested root_jobnet_actual as @root_jobnet_actual" do
      root_jobnet_actual = Tengine::Job::RootJobnetActual.create! valid_attributes
      get :show, :id => root_jobnet_actual.id.to_s
      assigns(:root_jobnet_actual).should eq(root_jobnet_actual)
    end
  end

  describe "GET new" do
    it "assigns a new root_jobnet_actual as @root_jobnet_actual" do
      get :new
      assigns(:root_jobnet_actual).should be_a_new(Tengine::Job::RootJobnetActual)
    end
  end

  describe "GET edit" do
    it "assigns the requested root_jobnet_actual as @root_jobnet_actual" do
      root_jobnet_actual = Tengine::Job::RootJobnetActual.create! valid_attributes
      get :edit, :id => root_jobnet_actual.id.to_s
      assigns(:root_jobnet_actual).should eq(root_jobnet_actual)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tengine::Job::RootJobnetActual" do
        expect {
          post :create, :root_jobnet_actual => valid_attributes
        }.to change(Tengine::Job::RootJobnetActual, :count).by(1)
      end

      it "assigns a newly created root_jobnet_actual as @root_jobnet_actual" do
        post :create, :root_jobnet_actual => valid_attributes
        assigns(:root_jobnet_actual).should be_a(Tengine::Job::RootJobnetActual)
        assigns(:root_jobnet_actual).should be_persisted
      end

      it "redirects to the created root_jobnet_actual" do
        post :create, :root_jobnet_actual => valid_attributes
        response.should redirect_to(Tengine::Job::RootJobnetActual.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved root_jobnet_actual as @root_jobnet_actual" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::RootJobnetActual.any_instance.stub(:save).and_return(false)
        post :create, :root_jobnet_actual => {}
        assigns(:root_jobnet_actual).should be_a_new(Tengine::Job::RootJobnetActual)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::RootJobnetActual.any_instance.stub(:save).and_return(false)
        post :create, :root_jobnet_actual => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested root_jobnet_actual" do
        root_jobnet_actual = Tengine::Job::RootJobnetActual.create! valid_attributes
        # Assuming there are no other tengine_job_root_jobnet_actuals in the database, this
        # specifies that the Tengine::Job::RootJobnetActual created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tengine::Job::RootJobnetActual.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => root_jobnet_actual.id, :root_jobnet_actual => {'these' => 'params'}
      end

      it "assigns the requested root_jobnet_actual as @root_jobnet_actual" do
        root_jobnet_actual = Tengine::Job::RootJobnetActual.create! valid_attributes
        put :update, :id => root_jobnet_actual.id, :root_jobnet_actual => valid_attributes
        assigns(:root_jobnet_actual).should eq(root_jobnet_actual)
      end

      it "redirects to the root_jobnet_actual" do
        root_jobnet_actual = Tengine::Job::RootJobnetActual.create! valid_attributes
        put :update, :id => root_jobnet_actual.id, :root_jobnet_actual => valid_attributes
        response.should redirect_to(root_jobnet_actual)
      end
    end

    describe "with invalid params" do
      it "assigns the root_jobnet_actual as @root_jobnet_actual" do
        root_jobnet_actual = Tengine::Job::RootJobnetActual.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::RootJobnetActual.any_instance.stub(:save).and_return(false)
        put :update, :id => root_jobnet_actual.id.to_s, :root_jobnet_actual => {}
        assigns(:root_jobnet_actual).should eq(root_jobnet_actual)
      end

      it "re-renders the 'edit' template" do
        root_jobnet_actual = Tengine::Job::RootJobnetActual.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::RootJobnetActual.any_instance.stub(:save).and_return(false)
        put :update, :id => root_jobnet_actual.id.to_s, :root_jobnet_actual => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested root_jobnet_actual" do
      root_jobnet_actual = Tengine::Job::RootJobnetActual.create! valid_attributes
      expect {
        delete :destroy, :id => root_jobnet_actual.id.to_s
      }.to change(Tengine::Job::RootJobnetActual, :count).by(-1)
    end

    it "redirects to the tengine_job_root_jobnet_actuals list" do
      root_jobnet_actual = Tengine::Job::RootJobnetActual.create! valid_attributes
      delete :destroy, :id => root_jobnet_actual.id.to_s
      response.should redirect_to(tengine_job_root_jobnet_actuals_url)
    end
  end

end
