require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Tengine::Job::ScriptActualsController do

  # This should return the minimal set of attributes required to create a valid
  # Tengine::Job::ScriptActual. As you add validations to Tengine::Job::ScriptActual, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all tengine_job_script_actuals as @tengine_job_script_actuals" do
      Tengine::Job::ScriptActual.delete_all
      script_actual = Tengine::Job::ScriptActual.create! valid_attributes
      get :index
      script_actuals = assigns(:script_actuals)
      script_actuals.to_a.should eq([script_actual])
    end
  end

  describe "GET show" do
    it "assigns the requested script_actual as @script_actual" do
      script_actual = Tengine::Job::ScriptActual.create! valid_attributes
      get :show, :id => script_actual.id.to_s
      assigns(:script_actual).should eq(script_actual)
    end
  end

  describe "GET new" do
    it "assigns a new script_actual as @script_actual" do
      get :new
      assigns(:script_actual).should be_a_new(Tengine::Job::ScriptActual)
    end
  end

  describe "GET edit" do
    it "assigns the requested script_actual as @script_actual" do
      script_actual = Tengine::Job::ScriptActual.create! valid_attributes
      get :edit, :id => script_actual.id.to_s
      assigns(:script_actual).should eq(script_actual)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tengine::Job::ScriptActual" do
        expect {
          post :create, :script_actual => valid_attributes
        }.to change(Tengine::Job::ScriptActual, :count).by(1)
      end

      it "assigns a newly created script_actual as @script_actual" do
        post :create, :script_actual => valid_attributes
        assigns(:script_actual).should be_a(Tengine::Job::ScriptActual)
        assigns(:script_actual).should be_persisted
      end

      it "redirects to the created script_actual" do
        post :create, :script_actual => valid_attributes
        response.should redirect_to(Tengine::Job::ScriptActual.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved script_actual as @script_actual" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::ScriptActual.any_instance.stub(:save).and_return(false)
        post :create, :script_actual => {}
        assigns(:script_actual).should be_a_new(Tengine::Job::ScriptActual)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::ScriptActual.any_instance.stub(:save).and_return(false)
        post :create, :script_actual => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested script_actual" do
        script_actual = Tengine::Job::ScriptActual.create! valid_attributes
        # Assuming there are no other tengine_job_script_actuals in the database, this
        # specifies that the Tengine::Job::ScriptActual created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tengine::Job::ScriptActual.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => script_actual.id, :script_actual => {'these' => 'params'}
      end

      it "assigns the requested script_actual as @script_actual" do
        script_actual = Tengine::Job::ScriptActual.create! valid_attributes
        put :update, :id => script_actual.id, :script_actual => valid_attributes
        assigns(:script_actual).should eq(script_actual)
      end

      it "redirects to the script_actual" do
        script_actual = Tengine::Job::ScriptActual.create! valid_attributes
        put :update, :id => script_actual.id, :script_actual => valid_attributes
        response.should redirect_to(script_actual)
      end
    end

    describe "with invalid params" do
      it "assigns the script_actual as @script_actual" do
        script_actual = Tengine::Job::ScriptActual.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::ScriptActual.any_instance.stub(:save).and_return(false)
        put :update, :id => script_actual.id.to_s, :script_actual => {}
        assigns(:script_actual).should eq(script_actual)
      end

      it "re-renders the 'edit' template" do
        script_actual = Tengine::Job::ScriptActual.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Job::ScriptActual.any_instance.stub(:save).and_return(false)
        put :update, :id => script_actual.id.to_s, :script_actual => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested script_actual" do
      script_actual = Tengine::Job::ScriptActual.create! valid_attributes
      expect {
        delete :destroy, :id => script_actual.id.to_s
      }.to change(Tengine::Job::ScriptActual, :count).by(-1)
    end

    it "redirects to the tengine_job_script_actuals list" do
      script_actual = Tengine::Job::ScriptActual.create! valid_attributes
      delete :destroy, :id => script_actual.id.to_s
      response.should redirect_to(tengine_job_script_actuals_url)
    end
  end

end
