# Tengineコンソール
tengine_console:
  # エンドツーエンドでアクセスするTengineコンソールのホスト名
  host: "http://localhost" 
  # エンドツーエンドでアクセスするTengineコンソールのポート番号
  port: 3000 

db:
  nodes:
    - host: "localhost"
      port: "27027"
      dbpath: "/mongodb_e2e/node0/data"
      logpath: "/mongodb_e2e/node0/log"
    - host: "localhost"
      port: "27028"
      dbpath: "/mongodb_e2e/node1/data"
      logpath: "/mongodb_e2e/node1/log"
    - host: "localhost"
      port: "27029"
      dbpath: "/mongodb_e2e/node2/data"
      logpath: "/mongodb_e2e/node2/log"
