#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

target = ARGV.first

result = `which #{target}`

unless result.empty?
  $stdout.puts("#{result} <$PATH: #{ENV['PATH']}>")
  exit(0)
end

$stderr.puts("#{target} not found in #{ENV['PATH']}")
exit(1)
