require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Tengine::Test::SshesController do

  # This should return the minimal set of attributes required to create a valid
  # Tengine::Test::Ssh. As you add validations to Tengine::Test::Ssh, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all tengine_test_sshes as @tengine_test_sshes" do
      Tengine::Test::Ssh.delete_all
      ssh = Tengine::Test::Ssh.create! valid_attributes
      get :index
      sshes = assigns(:sshes)
      sshes.to_a.should eq([ssh])
    end
  end

  describe "GET show" do
    it "assigns the requested ssh as @ssh" do
      ssh = Tengine::Test::Ssh.create! valid_attributes
      get :show, :id => ssh.id.to_s
      assigns(:ssh).should eq(ssh)
    end
  end

  describe "GET new" do
    it "assigns a new ssh as @ssh" do
      get :new
      assigns(:ssh).should be_a_new(Tengine::Test::Ssh)
    end
  end

  describe "GET edit" do
    it "assigns the requested ssh as @ssh" do
      ssh = Tengine::Test::Ssh.create! valid_attributes
      get :edit, :id => ssh.id.to_s
      assigns(:ssh).should eq(ssh)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tengine::Test::Ssh" do
        expect {
          post :create, :ssh => valid_attributes
        }.to change(Tengine::Test::Ssh, :count).by(1)
      end

      it "assigns a newly created ssh as @ssh" do
        post :create, :ssh => valid_attributes
        assigns(:ssh).should be_a(Tengine::Test::Ssh)
        assigns(:ssh).should be_persisted
      end

      it "redirects to the created ssh" do
        post :create, :ssh => valid_attributes
        response.should redirect_to(Tengine::Test::Ssh.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ssh as @ssh" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Test::Ssh.any_instance.stub(:save).and_return(false)
        post :create, :ssh => {}
        assigns(:ssh).should be_a_new(Tengine::Test::Ssh)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Test::Ssh.any_instance.stub(:save).and_return(false)
        post :create, :ssh => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ssh" do
        ssh = Tengine::Test::Ssh.create! valid_attributes
        # Assuming there are no other tengine_test_sshes in the database, this
        # specifies that the Tengine::Test::Ssh created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tengine::Test::Ssh.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => ssh.id, :ssh => {'these' => 'params'}
      end

      it "assigns the requested ssh as @ssh" do
        ssh = Tengine::Test::Ssh.create! valid_attributes
        put :update, :id => ssh.id, :ssh => valid_attributes
        assigns(:ssh).should eq(ssh)
      end

      it "redirects to the ssh" do
        ssh = Tengine::Test::Ssh.create! valid_attributes
        put :update, :id => ssh.id, :ssh => valid_attributes
        response.should redirect_to(ssh)
      end
    end

    describe "with invalid params" do
      it "assigns the ssh as @ssh" do
        ssh = Tengine::Test::Ssh.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Test::Ssh.any_instance.stub(:save).and_return(false)
        put :update, :id => ssh.id.to_s, :ssh => {}
        assigns(:ssh).should eq(ssh)
      end

      it "re-renders the 'edit' template" do
        ssh = Tengine::Test::Ssh.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tengine::Test::Ssh.any_instance.stub(:save).and_return(false)
        put :update, :id => ssh.id.to_s, :ssh => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ssh" do
      ssh = Tengine::Test::Ssh.create! valid_attributes
      expect {
        delete :destroy, :id => ssh.id.to_s
      }.to change(Tengine::Test::Ssh, :count).by(-1)
    end

    it "redirects to the tengine_test_sshes list" do
      ssh = Tengine::Test::Ssh.create! valid_attributes
      delete :destroy, :id => ssh.id.to_s
      response.should redirect_to(tengine_test_sshes_url)
    end
  end

end
